class MsUtils {
  static String getPathIcons(String path) {
    switch (path) {
      case "belongings.png":
        return "assets/images/belongings.png";
      case "bill.png":
        return "assets/images/bill.png";
      case "business.png":
        return "assets/images/business.png";
      case "contract.png":
        return "assets/images/contract.png";
      case "dog.png":
        return "assets/images/dog.png";
      case "donation.png":
        return "assets/images/donation.png";
      case "earnings.png":
        return "assets/images/earnings.png";
      case "education.png":
        return "assets/images/education.png";
      case "electricity-bill.png":
        return "assets/images/electricity-bill.png";
      case "game-controller.png":
        return "assets/images/game-controller.png";
      case "game.png":
        return "assets/images/game.png";
      case "gas-bill.png":
        return "assets/images/gas-bill.png";
      case "healthcare.png":
        return "assets/images/healthcare.png";
      case "house-1.png":
        return "assets/images/house-1.png";
      case "house-2.png":
        return "assets/images/house-2.png";
      case "house-bill.png":
        return "assets/images/house-bill.png";
      case "house.png":
        return "assets/images/house.png";
      case "investment.png":
        return "assets/images/investment.png";
      case "invoice-1.png":
        return "assets/images/invoice-1.png";
      case "invoice-2.png":
        return "assets/images/invoice-2.png";
      case "invoice.png":
        return "assets/images/invoice.png";
      case "joystick.png":
        return "assets/images/joystick.png";
      case "moving-truck.png":
        return "assets/images/moving-truck.png";
      case "online-medical.png":
        return "assets/images/online-medical.png";
      case "phone.png":
        return "assets/images/phone.png";
      case "pressure.png":
        return "assets/images/pressure.png";
      case "protection.png":
        return "assets/images/protection.png";
      case "reduce-cost.png":
        return "assets/images/reduce-cost.png";
      case "salary.png":
        return "assets/images/salary.png";
      case "service-management.png":
        return "assets/images/service-management.png";
      case "skincare.png":
        return "assets/images/skincare.png";
      case "snack.png":
        return "assets/images/snack.png";
      case "sports.png":
        return "assets/images/sports.png";
      case "transfer.png":
        return "assets/images/transfer.png";
      case "wage.png":
        return "assets/images/wage.png";
      case "water-bill.png":
        return "assets/images/water-bill.png";
      case "shopping-bag.png":
        return "assets/images/shopping-bag.png";
      case "box.png":
        return "assets/images/box.png";
    }
    return "assets/images/house.png";
  }
}
